version: "3.7"

services:
  database:
    image: postgres
    container_name: cnab_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cnab
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
